ifndef MAKEFILE_CONFIG
MAKEFILE_CONFIG=

#
#
#

CC = g++
CFLAGS= -g -Wall -I/usr/include/g++
ROOT_DIR= /home/pechy/Eternity/Source
THREADS= c_r

#.c.o		:
#	$(CC) $(CFLAGS) -c $(.IMPSRC)

#.PATH: $(ROOT_DIR)/Common $(ROOT_DIR)/Common/H

endif

