ifndef MAKEFILE_CONFIG
MAKEFILE_CONFIG=

#
#
#

CXX = g++
# Marek removed -g switch, 23.2.1999
#CXXFLAGS=  -Wall -g -I/usr/include/g++ 
CXXFLAGS=  -Wall -I/usr/include/g++ 
#CXXFLAGS= -Wall -g -I/usr/include/g++ -DOPERATOR_NEW_ARRAY
ROOT_DIR= /home/pechy/Eternity/Source
THREADS= c_r
STD= stdc++
MATH= m 
RSAEURO= rsaeuro 

# do not use more that 1 !! -> strange error can appear
MAKE=gmake -j 1

#.c.o		:
#	$(CC) $(CFLAGS) -c $(.IMPSRC)

#.PATH: $(ROOT_DIR)/Common $(ROOT_DIR)/Common/H

endif

