all2: test.cc
	g++ -g -o test test.cc ../Common/GMessage/gMessageAll.o ../Common/Debugable/debugableAll.o ../Common/LogFile/logFile.o ../Common/MessageQueue/messageQueueAll.o ../Common/Semaphore/semaphoreAll.o -lc_r 
all: pokus.cc
	g++ -g -o pokus pokus.cc ../Common/GMessage/gMessageAll.o ../Common/Debugable/debugableAll.o ../Common/LogFile/logFile.o ../Common/MessageQueue/messageQueueAll.o ../Common/Semaphore/semaphoreAll.o -lc_r 
